name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ESLint using yarn
      run: yarn add --dev eslint
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
