name: Unit Testing with Jest
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install jest through yarn
      run: yarn add --dev jest
    - name: Run jest unit tests
      run: yarn jest
