name: Jest Test
on:  
  push:
    branches:
      - master
      - timer-unit-tests
  pull_request:
    branches:
      - master
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
