name: Jest Unit Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install jest through yarn
      run: yarn add --dev jest
    - name: Run jest unit tests
      run: yarn jest
